### ISSUE TITLE
BBOX Padding feature request

### ISSUE THREAD

**Issue by deng-wei** [Ryuukeisyou/comfyui_face_parsing#10]
To handle scenarios requiring segmentation of long hair.
![2024-06-07_09-55](https://github.com/Ryuukeisyou/comfyui_face_parsing/assets/8124973/d80424f8-3c94-4678-b557-411bb1720b42)

**Comment by Ryuukeisyou** [comment]
hi. sorry i dont quite get the idea. currently the FaceBBoxDetect has a dilation parameter which controls how big the bbox is padded. can this meet your need?
