### ISSUE TITLE
Error occurred when executing FaceParse(FaceParsing)

### ISSUE THREAD

**Issue by WeirdScienceX** [Ryuukeisyou/comfyui_face_parsing#11]
0: 640x640 1 face, 9.0ms
Speed: 4.5ms preprocess, 9.0ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)
!!! Exception during processing!!! module 'matplotlib.cm' has no attribute 'get_cmap'
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_face_parsing\face_parsing_nodes.py", line 582, in main
    colormap = cm.get_cmap('viridis', 19)
               ^^^^^^^^^^^
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'

**Comment by SamKhoze** [comment]
I got the same error

**Comment by predest** [comment]
it appears that the latest version matplotlib 3.9.0 is not compatible with the node, I had to uninstall it and reinstall the previous version matplotlib-3.8.4, and the issue was resolved, however I have no idea whether this change will impact any other custom nodes.

**Comment by Ryuukeisyou** [comment]
sorry for the delay. the new commit has fixed this issuse.
