### ISSUE TITLE
Error occurred when executing FaceParse(FaceParsing):  module 'matplotlib.cm' has no attribute 'get_cmap'

### ISSUE THREAD

**Issue by piovis2023** [Ryuukeisyou/comfyui_face_parsing#12]
Hi 

Can anyone help with this error?:
Error occurred when executing FaceParse(FaceParsing):
module 'matplotlib.cm' has no attribute 'get_cmap'

So far I have:
I've installed all of the requirements.txt file
Uninstalled and re-installed the nodes
Restarted the server
Tried various versions of metalotlib

Full error message:
Error occurred when executing FaceParse(FaceParsing):

module 'matplotlib.cm' has no attribute 'get_cmap'

File "C:\Users\ai\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\ai\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\ai\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\ai\ComfyUI\custom_nodes\comfyui_face_parsing\face_parsing_nodes.py", line 582, in main
colormap = cm.get_cmap('viridis', 19)

Thank you

**Comment by Ryuukeisyou** [comment]
sorry for the delay. it seems that the new matplotlib 3.9 has removed the function. i have updated the code, and it should be fixed now.
