### ISSUE TITLE
Can we make the ColorAdjust(FaceParsing) node more visually friendly?

### ISSUE THREAD

**Issue by pandayummy** [Ryuukeisyou/comfyui_face_parsing#15]
![image](https://github.com/user-attachments/assets/150fb867-2097-4480-93fb-c0fe0fa8dff5)

This kind of parameter ajustment is not  "what you see is what you get".
Can we make it like Photoshop?

![image](https://github.com/user-attachments/assets/70af2ec9-aedd-4a51-a407-b36972182113)

**Comment by Ryuukeisyou** [comment]
i dont have the technique to make the js so there is no plan. maybe you can find other custom nodes that do the stuff.
