### ISSUE TITLE
What is the license of this?? Apache 2.0 license??

### ISSUE THREAD

**Issue by kdhckd** [Ryuukeisyou/comfyui_face_parsing#17]

**Comment by kdhckd** [comment]
MIT ? please write it on Readme. someone is needed

**Comment by Ryuukeisyou** [comment]
My own code is MIT, but the model itself is non commercial. You can refer to the model's page.

**Comment by razvanphp** [comment]
> but the model itself is non commercial.

Damn 🙁 you could mention this in the README tho.

**Comment by razvanphp** [comment]
Maybe we could train / use a model from this dataset? It's MIT Licensed.

https://github.com/Megvii-BaseDetection/4K-Face
