### ISSUE TITLE
the readme is not suitable

### ISSUE THREAD

**Issue by 892384750** [Ryuukeisyou/comfyui_face_parsing#2]
When I perform manual operations with reference to the current readme, the following error will occur. After checking the code, I found that it was a problem with the wrong path. Then I found that you updated the code two days ago. The operation of the readme should not be consistent with the current code. If the author If you have time, I hope you can update the readme file. Thank you very much.

![image](https://github.com/Ryuukeisyou/comfyui_face_parsing/assets/38170819/5ae44a93-1e89-49e3-8b4d-476a5e1e873d)
![image](https://github.com/Ryuukeisyou/comfyui_face_parsing/assets/38170819/e0bacfdb-dc8f-4963-b166-d3cb2650d2a0)

**Comment by TheMindExpansionNetwork** [comment]
same error so how do I fix this beast anyone have snippet for me please

**Comment by Ryuukeisyou** [comment]
@892384750 strange. it seems that the problem is in face_parsing_nodes.py line 24, where 'ultralytics_bbox' is not a valid key. however it works fine in my environment. can u try updating the comfyUI repo and see if things are right?
