### ISSUE TITLE
Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by Amazon90** [Ryuukeisyou/comfyui_face_parsing#23]
# ComfyUI Error Report
## Error Details
- **Node ID:** 80
- **Node Type:** FaceParsingModelLoader(FaceParsing)
- **Exception Type:** safetensors_rust.SafetensorError
- **Exception Message:** Error while deserializing header: MetadataIncompleteBuffer
## Stack Trace
```
  File "D:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\custom_nodes\comfyui_face_parsing\face_parsing_nodes.py", line 635, in main
    model = AutoModelForSemanticSegmentation.from_pretrained(face_parsing_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\venv\Lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\venv\Lib\site-packages\transformers\modeling_utils.py", line 3994, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.3.5-3-g0d4e29f
- **Arguments:** D:\ComfyUI\main.py --auto-launch --preview-method auto --disable-cuda-malloc --fast
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12878086144
  - **VRAM Free:** 11574181888
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

**Comment by Amazon90** [comment]
Do you mean for me to re-download the model from this path?
`ComfyUI\models\face_parsing\model.safetensors`

**Comment by Ryuukeisyou** [comment]
> Do you mean to redownload the model from this path? `ComfyUI\models\face_parsing\model.safetensors`

yes. plz follow readme and download the file.

**Comment by Amazon90** [comment]
Thank you, it is working now. Indeed, the file was corrupted during the automatic download, and the issue was resolved after re-downloading the face_parsing model
![1](https://github.com/user-attachments/assets/86c64328-58ca-4d7e-9a10-1b0a917409f5)

**Comment by Amazon90** [comment]
> > Do you mean to redownload the model from this path? `ComfyUI\models\face_parsing\model.safetensors`
> 
> yes. plz follow readme and download the file.

Thank you, it is working now. Indeed, the file was corrupted during the automatic download, and the issue was resolved after re-downloading the face_parsing model
![1](https://github.com/user-attachments/assets/86c64328-58ca-4d7e-9a10-1b0a917409f5)
