### ISSUE TITLE
workflow.

### ISSUE THREAD

**Issue by Tobe2d** [Ryuukeisyou/comfyui_face_parsing#3]
Can you share the workflow as the workflow.png doesnot load it into comfyui.

**Comment by Tobe2d** [comment]
[workflow (3).json](https://github.com/Ryuukeisyou/comfyui_face_parsing/files/14318816/workflow.3.json)

I re-created it and added compare at the end of it using rgthree node for before and after

**Comment by Ryuukeisyou** [comment]
> Can you share the workflow as the workflow.png doesnot load it into comfyui.

Actually you can. Just load an png generated by comfy-ui and you have it's workflow. By default pngs from comfy-ui has meta data that contains the workflow from which it's generated. The processed.png in readme is what you need.
