### ISSUE TITLE
not work well for find the face

### ISSUE THREAD

**Issue by amberfay** [Ryuukeisyou/comfyui_face_parsing#7]
![微信图片_20240409084955](https://github.com/Ryuukeisyou/comfyui_face_parsing/assets/35922114/9e9f98be-0a84-40df-84e8-8bc29d3224be)
when use it,  bbox does not find the right face,

**Comment by amberfay** [comment]
meet this problem when use batch images

**Comment by Ryuukeisyou** [comment]
hi. could you share the workflow so that i can try delve into the problem?
